import theme from "../../config/theme/theme";

export const ArticlesStyles = () => ({
  mainContent: {
    paddingBottom: 50,
    paddingLeft: 0,
    paddingRight: 0,
    maxWidth: "50%",

    [theme.breakpoints.down("sm")]: {
      paddingTop: 10,
      paddingBottom: 10,
      paddingLeft: 0,
      paddingRight: 0,
    },
  },

  titleArticles: {
    dispaly: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#1AAA8D",
    fontFamily: theme.typography.fontFamily,
    fontSize: 36,
  },
  articlesPoint: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 0,
    paddingRight: 0,
    listStyleType: "none",
    marginBottom: 0,
    "& li::before": {
      position: "absolute",
      fontFamily: theme.typography.fontFamily,
      fontWeight: 900,
      display: "block",
      left: "-31px",
      top: 0,
      width: 27,
      height: 27,
      lineHeight: 27,
      textAlign: "center",
      fontSize: 12,
      backgroundColor: "#c1a16c",
      color: "#FFFFFF",
      margin: 4,
      borderRadius: 450,
      content: `'\f054'`,
    },
    "& > li": {
      fontSize: 17,
      fontFamily: theme.typography.fontFamily,
      lineHeight: 1.6,
      position: "relative",
      padding: 4,
      minHeight: 27.6,
      marginLeft: 31,
      "&::before": {
        position: "absolute",
        fontFamily: theme.typography.fontFamily,
        fontWeight: 900,
        display: "block",
        left: "-31px",
        top: 0,
        width: 27,
        height: 27,
        lineHeight: 27,
        textAlign: "center",
        fontSize: 12,
        backgroundColor: "#c1a16c",
        color: "#FFFFFF",
        margin: 4,
        borderRadius: 450,
        content: `'\f054'`,
      },
    },
  },
  pointsContainer: {
    display: "flex",
    flexDirection: " column",
    minHeight: 100,
    paddingTop: "50px",
  },
  items: {

    fontSize: 22,
    fontFamily: theme.typography.fontFamily,
    lineHeight: 1.6,
    position: "relative",
    padding: 4,
    fontWeight:600,
    color:'brown',
    minHeight: 27.6,
    marginLeft: 31,
    "&::before": {
      position: "absolute",
      fontFamily: theme.typography.fontFamily,
      fontWeight: 900,
      display: "block",
      left: "-31px",
      top: 0,
      width: 27,
      height: 27,
      lineHeight: 27,
      textAlign: "center",
      fontSize: 12,
      backgroundColor: "#c1a16c",
      color: "#FFFFFF",
      margin: 4,
      borderRadius: 450,
      content: `'\f054'`,
    },
  },
  noProducts: {
    fontSize: 16,
    display: "flex",
    minHeigth: 40,
    margin: 20,
    color: theme.palette.primary.textBrow,
  },
});
